export enum SearchActions {
  SET_PLACE = "SET_PLACE",
  SET_CURRENT_RECOMMENDED_PLACE = "SET_CURRENT_RECOMMENDED_PLACE",
  SET_HAS_RECOMMENDED_PLACE_CHANGED = "SET_HAS_RECOMMENDED_PLACE_CHANGED",
  SET_FLIGHT_TYPE = "SET_FLIGHT_TYPE",
  SET_FLIGHT_SETTINGS = "SET_FLIGHT_SETTINGS",
  INCREMENT_ADULTS_NUMBER = "INCREMENT_ADULTS_NUMBER",
  INCREMENT_CHILDREN_NUMBER = "INCREMENT_CHILDREN_NUMBER",
  INCREMENT_INFANTS_NUMBER = "INCREMENT_INFANTS_NUMBER",
  DECREMENT_ADULTS_NUMBER = "DECREMENT_ADULTS_NUMBER",
  DECREMENT_CHILDREN_NUMBER = "DECREMENT_CHILDREN_NUMBER",
  DECREMENT_INFANTS_NUMBER = "DECREMENT_INFANTS_NUMBER",
  SET_CABIN_CLASS = "SET_CABIN_CLASS",
}
