export enum SearchActions {
  SET_FLIGHT_TYPE = "SET_FLIGHT_TYPE",
  SET_CABIN_CLASS = "SET_CABIN_CLASS",
  SET_PASSENGERS = "SET_PASSENGERS",
  SET_SEARCH_FORM_DATA = "SET_SEARCH_FORM_DATA",
  SET_LIMIT = "SET_LIMIT",
  SET_SHOW_RESULTS = "SET_SHOW_RESULTS",
  SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS",
  SET_VISIBLE_ITEMS = "SET_VISIBLE_ITEMS",
  SET_IS_FORM_SUBMITTING = "SET_IS_FORM_SUBMITTING",
  SET_PAGE = "SET_PAGE",
}
