export enum SearchActions {
  SET_PLACE = "SET_PLACE",
  SET_CURRENT_RECOMMENDED_PLACE = "SET_CURRENT_RECOMMENDED_PLACE",
  SET_HAS_RECOMMENDED_PLACE_CHANGED = "SET_HAS_RECOMMENDED_PLACE_CHANGED",
  SET_FLIGHT_TYPE = "SET_FLIGHT_TYPE",
}
