export type IconProps = {
  name:
    | 'adultIcon'
    | 'arrowIcon'
    | 'airplaneIcon'
    | 'burgerIcon'
    | 'childIcon'
    | 'cityIcon'
    | 'closeIcon'
    | 'copyIcon'
    | 'countryIcon'
    | 'githubIcon'
    | 'globeIcon'
    | 'infantIcon'
    | 'linkedinIcon'
    | 'logoIcon'
    | 'minusIcon'
    | 'plusIcon'
    | 'rarrowIcon'
    | 'sortFilterIcon'
    | 'tickIcon'
    | 'userIcon'
    | 'polishFlagImage'
    | 'dollarImage'
    | 'euroImage'
    | 'planetEarthImage'
    | 'poundImage'
    | 'signInImage'
    | 'signOutImage'
    | 'usaFlagImage'
    | 'zlotyImage'
    | 'customImage';
  width?: number;
  height?: number;
  fill?: string;
  color?: string;
  src?: string;
  alt?: string;
};
